USE `thryver`;

DROP TABLE IF EXISTS `question_user_answers`;
CREATE TABLE `question_user_answers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL,
  `question_id` bigint(20) unsigned NOT NULL,
  `answer` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_question` (`question_id`),
  KEY `FK_users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;



DROP TABLE IF EXISTS `questions`;
CREATE TABLE `questions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `option` varchar(255) DEFAULT NULL COMMENT 'Question Title',
  `type` enum('Career','Personal') DEFAULT NULL COMMENT 'Career/Personal',
  `test_section_id` bigint(20) unsigned NOT NULL COMMENT 'Section Number',
  `category` enum('R','I','A','S','E','C','Op','Co','Ex','Ag','Ne') DEFAULT NULL COMMENT 'A,I,R,S,E,C (For Career), Personal (Op,Co, Ex, Ag,Ne)',
  `reverse_score` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `FK_questions` (`test_section_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

INSERT INTO `questions` (`option`, `type`, `test_section_id`, `category`, `reverse_score`) VALUES
('I enjoy influencing, persuading, and leading.', NULL, 1, 'E', 0),
('I am confident when it comes to connecting with people, promoting ideas, or negotiating.', NULL, 1, 'E', 0),
('I like to start projects, and I enjoy the feeling of accomplishing what I set out to do.', NULL, 1, 'E', 0),
('I enjoy helping, serving, teaching, or training others.', NULL, 1, 'S', 0),
('I can be a cooperative member of a work team, athletic team, or committee.', NULL, 1, 'S', 0),
('I could enjoy working with children, the elderly, or people with special needs.', NULL, 1, 'S', 0),
('I like to work with my hands to build, fix, or improve things.', NULL, 1, 'R', 0),
('I am good at practical activities such as mechanical and structural work, troubleshooting equipment, farming or gardening.', NULL, 1, 'R', 0),
('I enjoy being physically active, playing sports, or being outdoors.', NULL, 1, 'R', 0),
('I enjoy creating new and original ideas, expressions, or methods.', NULL, 1, 'A', 0),
('I like to attend concerts, theatre, and art galleries or showings.', NULL, 1, 'A', 0),
('I have interest and skill in writing, fashion, performing, drawing or design.', NULL, 1, 'A', 0),
('I am detail-oriented and enjoy working with information.', NULL, 1, 'C', 0),
('I am good at following instructions or procedures carefully.', NULL, 1, 'C', 0),
('I like to work with budgets and other controls to keep things in order.', NULL, 1, 'C', 0),
('I like to explore, observe, analyze and understand things.', NULL, 1, 'I', 0),
('I enjoy reading, investigating and research.', NULL, 1, 'I', 0),
('I am good at math or science, and I could be adept at using scientific or other special equipment.', NULL, 1, 'I', 0),
('act in plays', NULL, 3, 'A', 0),
('analyze things like problems, situations or trends', NULL, 3, 'I', 0),
('assist people who have special needs', NULL, 3, 'S', 0),
('attend concerts, theaters or art exhibits', NULL, 3, 'A', 0),
('be a leader', NULL, 3, 'E', 0),
('be creative', NULL, 3, 'A', 0),
('build things', NULL, 3, 'R', 0),
('care for disabled or sick people', NULL, 3, 'S', 0),
('comfort people who are troubled', NULL, 3, 'S', 0),
('cook', NULL, 3, 'R', 0),
('do creative writing', NULL, 3, 'A', 0),
('do experiments', NULL, 3, 'I', 0),
('draw', NULL, 3, 'A', 0),
('figure out how things work', NULL, 3, 'I', 0),
('have clear instructions to follow', NULL, 3, 'C', 0),
('have my day structured', NULL, 3, 'C', 0),
('help people solve their problems', NULL, 3, 'S', 0),
('influence or persuade people', NULL, 3, 'E', 0),
('keep records of my work', NULL, 3, 'C', 0),
('keep stuff like books, bills and clothing organized', NULL, 3, 'C', 0),
('make speeches or presentations', NULL, 3, 'E', 0),
('negotiate good deals when I buy or sell', NULL, 3, 'E', 0),
('organize things like files, offices or activities', NULL, 3, 'C', 0),
('pay attention to details', NULL, 3, 'C', 0),
('play instruments or sing', NULL, 3, 'A', 0),
('provide counsel and support to others', NULL, 3, 'S', 0),
('put things together or assemble models', NULL, 3, 'R', 0),
('read fiction, poetry or plays', NULL, 3, 'A', 0),
('set goals for myself', NULL, 3, 'E', 0),
('solve puzzles', NULL, 3, 'I', 0),
('take care of animals', NULL, 3, 'R', 0),
('take on new responsibilities', NULL, 3, 'E', 0),
('teach, tutor or help people learn', NULL, 3, 'S', 0),
('think things through before making decisions', NULL, 3, 'R', 0),
('visualize starting my own business', NULL, 3, 'E', 0),
('volunteer for teams that serve people in need', NULL, 3, 'S', 0),
('work mostly in an office', NULL, 3, 'C', 0),
('work mostly outdoors', NULL, 3, 'R', 0),
('work on cars', NULL, 3, 'R', 0),
('work on math problems', NULL, 3, 'I', 0),
('work on science projects', NULL, 3, 'I', 0),
('work with numbers or charts', NULL, 3, 'I', 0),
('be sensitive to people''s feelings', NULL, 4, 'S', 0),
('build, fix or maintain things', NULL, 4, 'R', 0),
('check to make sure standards are met', NULL, 4, 'C', 0),
('come up with new and different ideas', NULL, 4, 'A', 0),
('conduct thorough research', NULL, 4, 'I', 0),
('convince people to do things my way', NULL, 4, 'E', 0),
('cooperate well with others', NULL, 4, 'S', 0),
('create fiction, scripts, poetry, music, film, or video', NULL, 4, 'A', 0),
('create persuasive business presentations', NULL, 4, 'E', 0),
('find original ways to express myself', NULL, 4, 'A', 0),
('get things organized and keep them in order', NULL, 4, 'C', 0),
('give talks or speeches', NULL, 4, 'E', 0),
('handle a lot of details efficiently', NULL, 4, 'C', 0),
('handle physical tasks', NULL, 4, 'R', 0),
('investigate and solve complex problems', NULL, 4, 'I', 0),
('keep accurate records', NULL, 4, 'C', 0),
('learn and use various software tools', NULL, 4, 'I', 0),
('listen to both sides and mediate a dispute', NULL, 4, 'S', 0),
('operate power tools and equipment', NULL, 4, 'R', 0),
('patiently teach or train others', NULL, 4, 'S', 0),
('sell things or promote ideas', NULL, 4, 'E', 0),
('sing, act, dance, or create music', NULL, 4, 'A', 0),
('sketch, draw, paint, or design', NULL, 4, 'A', 0),
('solve mechanical problems', NULL, 4, 'R', 0),
('start and lead projects', NULL, 4, 'E', 0),
('tolerate rough weather', NULL, 4, 'R', 0),
('understand the problems of others', NULL, 4, 'S', 0),
('use scientific methods or instruments', NULL, 4, 'I', 0),
('work according to a set routine', NULL, 4, 'C', 0),
('work with abstract ideas and theories', NULL, 4, 'I', 0),
('a hands-on "doer"', NULL, 5, 'R', 0),
('ambitious', NULL, 5, 'E', 0),
('an outdoors person', NULL, 5, 'R', 0),
('analytical', NULL, 5, 'I', 0),
('artistically talented', NULL, 5, 'A', 0),
('assertive', NULL, 5, 'E', 0),
('athletic', NULL, 5, 'R', 0),
('caring', NULL, 5, 'S', 0),
('compassionate', NULL, 5, 'S', 0),
('convincing', NULL, 5, 'E', 0),
('creative', NULL, 5, 'A', 0),
('dependable', NULL, 5, 'C', 0),
('detail-oriented', NULL, 5, 'C', 0),
('efficient', NULL, 5, 'C', 0),
('empathetic', NULL, 5, 'S', 0),
('energetic', NULL, 5, 'E', 0),
('enthusiastic', NULL, 5, 'E', 0),
('explorative', NULL, 5, 'I', 0),
('fascinated by knowledge', NULL, 5, 'I', 0),
('cooperative', NULL, 5, 'S', 0),
('good at fixing things', NULL, 5, 'R', 0),
('good with tools and equipment', NULL, 5, 'R', 0),
('helpful', NULL, 5, 'S', 0),
('idealistic', NULL, 5, 'A', 0),
('imaginative', NULL, 5, 'A', 0),
('insightful', NULL, 5, 'I', 0),
('intellectually curious', NULL, 5, 'I', 0),
('intellectually skeptical', NULL, 5, 'I', 0),
('intuitive', NULL, 5, 'A', 0),
('inventive', NULL, 5, 'A', 0),
('leadership-oriented', NULL, 5, 'E', 0),
('mechanically inclined', NULL, 5, 'R', 0),
('methodical', NULL, 5, 'C', 0),
('nurturing', NULL, 5, 'S', 0),
('observant', NULL, 5, 'I', 0),
('open-minded', NULL, 5, 'A', 0),
('orderly', NULL, 5, 'C', 0),
('original', NULL, 5, 'A', 0),
('persuasive', NULL, 5, 'E', 0),
('physically tough', NULL, 5, 'R', 0),
('practical', NULL, 5, 'R', 0),
('precise', NULL, 5, 'C', 0),
('scientific', NULL, 5, 'I', 0),
('self-confident', NULL, 5, 'E', 0),
('structured', NULL, 5, 'C', 0),
('understanding', NULL, 5, 'S', 0),
('very careful', NULL, 5, 'C', 0),
('warmhearted', NULL, 5, 'S', 0),
('I stay cool under pressure. ', NULL, 2, 'Ne', 1),
('I try creative approaches. ', NULL, 2, 'Op', 0),
('I am satisfied with how my life is going...', NULL, 2, 'Ne', 1),
('It bothers me when I am treated unfairly...', NULL, 2, 'Ne', 0),
('I know how to get people interested. ', NULL, 2, 'Ex', 0),
('I skip things that aren''t important. ', NULL, 2, 'Co', 1),
('Being around people energizes me.', NULL, 2, 'Ex', 0),
('I look at things from other points of vi...', NULL, 2, 'Op', 0),
('I enjoy artistic expression. ', NULL, 2, 'Op', 0),
('I don''t fret over the details.', NULL, 2, 'Co', 1),
('I can be assertive and convincing.', NULL, 2, 'Ex', 0),
('I avoid drawing attention to myself. ', NULL, 2, 'Ex', 1),
('I like to be precise and get all the det...', NULL, 2, 'Co', 0),
('I prefer plain speech to poetry. ', NULL, 2, 'Op', 1),
('I would rather be accurate than nice. ', NULL, 2, 'Ag', 1),
('I tend to work best on my own. ', NULL, 2, 'Ex', 1),
('I make plans and stick to them.', NULL, 2, 'Co', 0),
('I get worried or concerned sometimes.', NULL, 2, 'Ne', 0),
('I find it best to stick with what I know...', NULL, 2, 'Op', 1),
('I rarely get stressed.', NULL, 2, 'Ne', 1),
('I accept people as they are. ', NULL, 2, 'Ag', 0),
('I go with the flow.', NULL, 2, 'Co', 1),
('I let people know when I disagree with t...', NULL, 2, 'Ag', 1),
('I have some regrets.', NULL, 2, 'Ne', 0),
('I like regular routines and methods that...', NULL, 2, 'Op', 1),
('I can be skeptical of others'' motives. ', NULL, 2, 'Ag', 1),
('I sympathize with others'' feelings. ', NULL, 2, 'Ag', 0),
('I believe that others have good intentio...', NULL, 2, 'Ag', 0),
('I don''t mind letting others do the talki...', NULL, 2, 'Ex', 1),
('I am disciplined and deliberate.', NULL, 2, 'Co', 0);

ALTER TABLE `questions`
  ADD CONSTRAINT `FK_questions` FOREIGN KEY (`test_section_id`) REFERENCES `test_sections` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `question_user_answers`
  ADD CONSTRAINT `FK_question` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
